name: Generate snake

on:
  schedule:
    - cron: "00 22 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update snake grid
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.SNAKE_PROFILE_TOKEN }}
      - uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: snake
          commit_message: Update snake
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.SNAKE_PROFILE_TOKEN }}
